### ISSUE TITLE
set is_bot checker to new user when adding new user as someone's referee

### ISSUE THREAD

**Issue by lllumineux** [summer-school-2019/money-bot#26]
p.s. yeah, the label is pretty weird though, but i got it and that's all that needed here

**Comment by Birdi7** [comment]
it's useless, as a bot can't see the other bot's messages. Check [this](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots) 
So, I close it

**Comment by lllumineux** [comment]
rly? didn't know that... okay then
