### ISSUE TITLE
ValidationError({'last_name': ['Field may not be null.']})

### ISSUE THREAD

**Issue by lllumineux** [summer-school-2019/money-bot#29]
https://github.com/summer-school-2019/money-bot/blob/6ea2495cf9bbc19d992584df474a0ea009145caf/money_bot/utils/update_middleware.py#L11

Some users may not have last_name, @BardRandall, fix it

**Comment by lllumineux** [comment]
btw username and first_name should be fixed too

**Comment by BardRandall** [comment]
I can set None for these field, but then you have to check them before usage

**Comment by lllumineux** [comment]
aight, but let's do it a bit later
