### ISSUE TITLE
rename to register_handlers

### ISSUE THREAD

**Issue by Birdi7** [summer-school-2019/money-bot#32]
https://github.com/summer-school-2019/money-bot/blob/dd71fd62f8b5c280b86390cce79a6a34e81db3b6/money_bot/utils/register_all_handlers.py#L7

**Comment by BardRandall** [comment]
It was fixed there: https://github.com/summer-school-2019/money-bot/pull/31/commits/fd6a2118025b7b952794d798d1e0bc9f279b0ea1
